# Generated by Django 2.1.1 on 2018-10-07 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wikipages', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wikipage',
            options={'ordering': ['updated_at'], 'verbose_name': 'WikiPage', 'verbose_name_plural': 'WikiPages'},
        ),
    ]
